#!/bin/sh
usage() {
 cat<<HERE

 gast_check performs a series of SQL queries to report counts FROM the gast tables.
 Results are sent to the screen.

 Usage: `basename $0` rundate region
 e.g. gast_check 20101119 v6v4

HERE
}

if [ -z $1 ]; then
  usage
  exit
fi

# mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct read_id) FROM gast_$1_$2 WHERE refhvr_id = '0' AND distance = '1'" 
# mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(read_id) FROM trimseq_not_deleted JOIN run using(run_id) JOIN source using(source_id) WHERE run = '$1' AND source = '$2'" 
# mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct read_id) FROM gast_$1_$2"
# mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct gast.read_id) FROM gast JOIN trimseq_not_deleted using(read_id) JOIN run using(run_id) JOIN source using(source_id) WHERE run = '$1' AND source = '$2'"
# mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(gast_concat.read_id) FROM gast_concat JOIN trimseq_not_deleted using(read_id) JOIN run using(run_id) JOIN source using(source_id) WHERE run = '$1' AND source = '$2'"

mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct read_id) as no_hit FROM gast_$1_$2 WHERE refhvr_id = '0' AND distance = '1'" 
mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(read_id) as total_trimseq FROM trimseq JOIN run using(run_id) JOIN dna_region using(dna_region_id) WHERE run = '$1' AND dna_region = '$2'" 
mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct read_id) as total_gast_$1_$2 FROM gast_$1_$2"
mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(distinct gast.read_id) as total_gast_trimseq FROM gast JOIN trimseq using(read_id) JOIN run using(run_id) JOIN dna_region using(dna_region_id) WHERE run = '$1' AND dna_region = '$2'"
mysql -h newbpcdb2.mbl.edu env454 -e "SELECT count(gast_concat.read_id) as total_gast_concat_trimseq FROM gast_concat JOIN trimseq using(read_id) JOIN run using(run_id) JOIN dna_region using(dna_region_id) WHERE run = '$1' AND dna_region = '$2'"

exit
